import "server-only";

// Supabase Storage for product and recipe photos (bucket "product-images").
// Visitors never talk to Supabase directly: images are served by the app at /media/<path>,
// so the Supabase API can stay private on the server.
export const BUCKET = "product-images";
export const MAX_IMAGE_BYTES = 5 * 1024 * 1024;
export const IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp", "image/avif"] as const;

const base = () => (process.env.SUPABASE_URL ?? "").replace(/\/+$/, "");
const key = () => process.env.SUPABASE_SECRET_KEY ?? "";

export const storageConfigured = () => base() !== "";
export const uploadsConfigured = () => base() !== "" && key() !== "";

/** Object paths are generated by us: lowercase slug segments plus a file name. */
export const SAFE_PATH = /^[a-z0-9][a-z0-9-]*(\/[a-z0-9][a-z0-9._-]*)+$/;

/**
 * Browser URL for a stored image id. Ids starting with "/" are files under /public;
 * anything else is an object path in the bucket. Returns null when it cannot be shown.
 */
export function imageSrc(id: string | null | undefined): string | null {
  if (!id) return null;
  if (id.startsWith("/")) return id;
  return storageConfigured() && SAFE_PATH.test(id) ? `/media/${id}` : null;
}

export function publicObjectUrl(path: string) {
  return `${base()}/storage/v1/object/public/${BUCKET}/${path}`;
}

export async function uploadObject(path: string, body: Blob, contentType: string) {
  const res = await fetch(`${base()}/storage/v1/object/${BUCKET}/${path}`, {
    method: "POST",
    headers: { apikey: key(), Authorization: `Bearer ${key()}`, "Content-Type": contentType, "x-upsert": "false", "cache-control": "31536000" },
    body,
    signal: AbortSignal.timeout(30_000),
  });
  if (!res.ok) throw new Error(`Storage upload failed: ${res.status}`);
}

export async function deleteObject(path: string) {
  const res = await fetch(`${base()}/storage/v1/object/${BUCKET}`, {
    method: "DELETE",
    headers: { apikey: key(), Authorization: `Bearer ${key()}`, "Content-Type": "application/json" },
    body: JSON.stringify({ prefixes: [path] }),
    signal: AbortSignal.timeout(15_000),
  });
  if (!res.ok) throw new Error(`Storage delete failed: ${res.status}`);
}
